// Executive deck definition shared by the in-app carousel, the file exports
// and the Google Slides export server function. The deck is built from the
// selected night's dataset so every date produces its own deck.

import type { NightDataset } from "@/lib/nightpulse-data";

export type DeckSlide = {
  kicker: string;
  title: string;
  summary: string;
  metrics: { label: string; value: string }[];
  bullets: string[];
  footnote: string;
};

export type Deck = {
  title: string;
  subtitle: string;
  slides: DeckSlide[];
};

const money = (value: number) => `$${value.toLocaleString()}`;

function find(dataset: NightDataset, label: string) {
  return dataset.operationalRead.find((item) => item.label === label)?.value ?? "—";
}

function kpi(dataset: NightDataset, id: string) {
  return dataset.kpis.find((k) => k.id === id);
}

export function buildDeck(dataset: NightDataset): Deck {
  const revenue = kpi(dataset, "revenue");
  const attendance = kpi(dataset, "attendance");
  const vip = kpi(dataset, "vip");
  const door = kpi(dataset, "door");
  const topDrinks = dataset.drinks.slice(0, 4);

  return {
    title: "NightPulse AI — LIV Miami, Friday Night Recap",
    subtitle: `Operations & revenue intelligence · ${dataset.date}`,
    slides: [
      {
        kicker: "01 · Financial",
        title: "Weekend Financial Overview & Pacing",
        summary: dataset.deck.financial.summary,
        metrics: [
          { label: "Gross Revenue", value: dataset.totalRevenueLabel },
          { label: "vs Target", value: revenue?.delta ?? "—" },
          { label: "VIP Spend", value: vip?.delta ?? "—" },
          { label: "Avg Check (VIP)", value: find(dataset, "VIP Average Check") },
        ],
        bullets: dataset.deck.financial.bullets,
        footnote: "Source: POS + door scan reconciliation, audit mode",
      },
      {
        kicker: "02 · Beverage",
        title: "Bar & Bottle Service Breakdown",
        summary: dataset.deck.beverage.summary,
        metrics: topDrinks.map((d) => ({ label: d.name, value: money(d.revenue) })),
        bullets: dataset.deck.beverage.bullets,
        footnote: "Top 5 products by gross revenue",
      },
      {
        kicker: "03 · Door",
        title: "Door Flow & Demographic Timing",
        summary: dataset.deck.door.summary,
        metrics: [
          { label: "Attendance", value: attendance?.value ?? "—" },
          { label: "Occupancy Peak", value: find(dataset, "Occupancy Peak") },
          { label: "Peak Wait", value: find(dataset, "Peak Queue Wait") },
          { label: "Gender Split", value: door?.value ?? "—" },
        ],
        bullets: dataset.deck.door.bullets,
        footnote: "Source: scanner telemetry, 10 PM – 4 AM",
      },
      {
        kicker: "04 · Actions",
        title: "AI Recommendations for Next Weekend",
        summary: dataset.deck.actions.summary,
        metrics: dataset.deck.actions.metrics,
        bullets: dataset.deck.actions.bullets,
        footnote: `Generated by NightPulse AI from ${dataset.date}'s audit data`,
      },
    ],
  };
}

export function deckToMarkdown(deck: Deck): string {
  const lines: string[] = [`# ${deck.title}`, "", `_${deck.subtitle}_`, ""];
  for (const slide of deck.slides) {
    lines.push(`## ${slide.kicker} — ${slide.title}`, "", slide.summary, "");
    lines.push(slide.metrics.map((m) => `**${m.label}:** ${m.value}`).join(" · "), "");
    for (const bullet of slide.bullets) lines.push(`- ${bullet}`);
    lines.push("", `> ${slide.footnote}`, "");
  }
  return lines.join("\n");
}

export function deckToBrief(deck: Deck): string {
  const lines = [deck.title, deck.subtitle, ""];
  for (const slide of deck.slides) {
    lines.push(`${slide.title}: ${slide.summary}`);
    lines.push(...slide.bullets.map((b) => `  • ${b}`));
    lines.push("");
  }
  return lines.join("\n");
}
