// Executive deck definition shared by the in-app carousel, the file exports
// and the Google Slides export server function.

export type DeckSlide = {
  kicker: string;
  title: string;
  summary: string;
  metrics: { label: string; value: string }[];
  bullets: string[];
  footnote: string;
};

export type Deck = {
  title: string;
  subtitle: string;
  slides: DeckSlide[];
};

export const EXECUTIVE_DECK: Deck = {
  title: "NightPulse AI — LIV Miami, Friday Night Recap",
  subtitle: "Operations & revenue intelligence · Friday, August 21",
  slides: [
    {
      kicker: "01 · Financial",
      title: "Weekend Financial Overview & Pacing",
      summary:
        "Gross revenue closed at $68,450, 18% ahead of target, carried by a 92% VIP table sell-through.",
      metrics: [
        { label: "Gross Revenue", value: "$68,450" },
        { label: "vs Target", value: "+18%" },
        { label: "VIP Spend", value: "$38,500" },
        { label: "Avg Check (VIP)", value: "$1,750" },
      ],
      bullets: [
        "VIP bottle service delivered 56% of revenue ($38,332) from 22 of 24 tables.",
        "General admission contributed $16,428 (24%); main bar $13,690 (20%).",
        "Highest single table: $6,200 (Table 12) — repeat host relationship.",
        "Pacing held above target from 11:30 PM onward; no late-night revenue drop-off.",
      ],
      footnote: "Source: POS + door scan reconciliation, audit mode",
    },
    {
      kicker: "02 · Beverage",
      title: "Bar & Bottle Service Breakdown",
      summary:
        "Premium tequila drove the bar; the highest-margin cocktail is also the least promoted.",
      metrics: [
        { label: "Don Julio 1942", value: "$18,400" },
        { label: "Clase Azul", value: "$8,400" },
        { label: "Veuve Clicquot", value: "$6,650" },
        { label: "Espresso Martini", value: "$4,708" },
      ],
      bullets: [
        "Don Julio 1942: 46 units, 71% margin — anchor of the bottle menu.",
        "Clase Azul Reposado: 21 units at 68% margin; strong second tier.",
        "Veuve Clicquot: 38 units, 62% margin — highest volume, lowest margin of the top 3.",
        "Espresso Martini at 78% margin is the biggest upside: promote at the door and on table menus.",
      ],
      footnote: "Top 5 products by gross revenue",
    },
    {
      kicker: "03 · Door",
      title: "Door Flow & Demographic Timing",
      summary:
        "Arrivals concentrated between 11:30 PM and 1:00 AM, pushing peak queue wait to 22 minutes.",
      metrics: [
        { label: "Attendance", value: "1,240" },
        { label: "Occupancy Peak", value: "12:45 AM" },
        { label: "Peak Wait", value: "22 min" },
        { label: "Gender Split", value: "49% M / 51% F" },
      ],
      bullets: [
        "68% of all entries landed inside the 90-minute peak arrival window.",
        "Door deployment: 6 scanners, 4 ID checkers, 2 list hosts (12 staff).",
        "Queue wait exceeded 20 minutes from 11:40 PM to 12:20 AM.",
        "Gender balance stayed on target all night without door intervention.",
      ],
      footnote: "Source: scanner telemetry, 10 PM – 4 AM",
    },
    {
      kicker: "04 · Actions",
      title: "AI Recommendations for Next Weekend",
      summary: "Four operational moves projected to lift revenue and cut peak friction.",
      metrics: [
        { label: "Door Staff", value: "+2 scanners" },
        { label: "Margin Push", value: "Espresso Martini" },
        { label: "VIP Target", value: "24 / 24" },
        { label: "Focus Window", value: "11:30 PM – 1 AM" },
      ],
      bullets: [
        "Shift 2 scanners from the 2 AM block to 11:15 PM to cut peak wait below 12 minutes.",
        "Promote the Espresso Martini (78% margin) as the featured cocktail on table and bar menus.",
        "Pre-sell the two unsold VIP tables with a $1,750 minimum to close the 22/24 gap.",
        "Hold current door policy — gender balance and pacing both met target unassisted.",
      ],
      footnote: "Generated by NightPulse AI from Friday's audit data",
    },
  ],
};

export function deckToMarkdown(deck: Deck): string {
  const lines: string[] = [`# ${deck.title}`, "", `_${deck.subtitle}_`, ""];
  for (const slide of deck.slides) {
    lines.push(`## ${slide.kicker} — ${slide.title}`, "", slide.summary, "");
    lines.push(slide.metrics.map((m) => `**${m.label}:** ${m.value}`).join(" · "), "");
    for (const bullet of slide.bullets) lines.push(`- ${bullet}`);
    lines.push("", `> ${slide.footnote}`, "");
  }
  return lines.join("\n");
}

export function deckToBrief(deck: Deck): string {
  const lines = [deck.title, deck.subtitle, ""];
  for (const slide of deck.slides) {
    lines.push(`${slide.title}: ${slide.summary}`);
    lines.push(...slide.bullets.map((b) => `  • ${b}`));
    lines.push("");
  }
  return lines.join("\n");
}
